sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-skelcd-control-sled-image .
script:
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" yast-skelcd-control-sled-image ./.travis.sh
